- name: filters
  hosts: local
  connection : local
  vars:
    topic : linux,shell,ansible
    tags:
      name: ansible
      project : roboshop  
  tasks :
    - name: filters
      ansible.builtin.debug:
        msg: "Hi ,{{Greeting | default('Good Morning')}}"

    - name: convert string into list
      ansible.builtin.debug:
        msg : "{{topic | split(',')}}"

    - name: convert map into list
      ansible.builtin.debug:
        msg: "{{tags| dict2items}}"

    - name: read json filters
      ansible.builtin.set_fact:
       students_yaml: "{{lookup('file','student.yaml') | from_yaml }}"

    - name: convert yaml to json
      ansible.builtin.debug:
       msg : "{{students_yaml | to_nice_json}}"